[2024-12-27T11:43:55.390+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-27T11:43:55.695+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_movies manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-27T11:43:55.715+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_movies manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-27T11:43:55.719+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-27T11:43:55.758+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_movies> on 2024-12-27 11:38:32.797674+00:00
[2024-12-27T11:43:55.768+0000] {standard_task_runner.py:72} INFO - Started process 1083 to run task
[2024-12-27T11:43:55.778+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_movies', 'manual__2024-12-27T11:38:32.797674+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmppf6tkuyi']
[2024-12-27T11:43:55.785+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask scrape_movies
[2024-12-27T11:43:56.005+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_movies manual__2024-12-27T11:38:32.797674+00:00 [running]> on host 1712831d7ea4
[2024-12-27T11:43:56.405+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_movies' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T11:38:32.797674+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T11:38:32.797674+00:00'
[2024-12-27T11:43:56.410+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-27T11:43:58.384+0000] {extract.py:56} INFO - Iteration: 0, release id: rl1511097089
[2024-12-27T11:44:12.775+0000] {extract.py:56} INFO - Iteration: 1, release id: rl2537783297
[2024-12-27T11:44:16.215+0000] {extract.py:98} ERROR - Failed iteration 1 for movie release id: rl2537783297
[2024-12-27T11:44:16.221+0000] {extract.py:99} ERROR - Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x5565781678fa <unknown>
#1 0x556577c78b7d <unknown>
#2 0x556577c6245e <unknown>
#3 0x556577c6165e <unknown>
#4 0x556577c60dd6 <unknown>
#5 0x556577c60cce <unknown>
#6 0x556577c5ed06 <unknown>
#7 0x556577c5f4ef <unknown>
#8 0x556577c6ed87 <unknown>
#9 0x556577c85bb4 <unknown>
#10 0x556577c8ba4b <unknown>
#11 0x556577c5fbf7 <unknown>
#12 0x556577c85701 <unknown>
#13 0x556577d0a8df <unknown>
#14 0x556577ceb893 <unknown>
#15 0x556577cba30d <unknown>
#16 0x556577cbb32e <unknown>
#17 0x55657813400b <unknown>
#18 0x556578137f97 <unknown>
#19 0x55657812071c <unknown>
#20 0x556578138b17 <unknown>
#21 0x5565781056cf <unknown>
#22 0x5565781566b8 <unknown>
#23 0x556578156880 <unknown>
#24 0x556578166776 <unknown>
#25 0x7faf68d181c4 <unknown>
Traceback (most recent call last):
  File "/opt/src/extract.py", line 84, in movie_page_extract
    driver.get(movie_link_imdb)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x5565781678fa <unknown>
#1 0x556577c78b7d <unknown>
#2 0x556577c6245e <unknown>
#3 0x556577c6165e <unknown>
#4 0x556577c60dd6 <unknown>
#5 0x556577c60cce <unknown>
#6 0x556577c5ed06 <unknown>
#7 0x556577c5f4ef <unknown>
#8 0x556577c6ed87 <unknown>
#9 0x556577c85bb4 <unknown>
#10 0x556577c8ba4b <unknown>
#11 0x556577c5fbf7 <unknown>
#12 0x556577c85701 <unknown>
#13 0x556577d0a8df <unknown>
#14 0x556577ceb893 <unknown>
#15 0x556577cba30d <unknown>
#16 0x556577cbb32e <unknown>
#17 0x55657813400b <unknown>
#18 0x556578137f97 <unknown>
#19 0x55657812071c <unknown>
#20 0x556578138b17 <unknown>
#21 0x5565781056cf <unknown>
#22 0x5565781566b8 <unknown>
#23 0x556578156880 <unknown>
#24 0x556578166776 <unknown>
#25 0x7faf68d181c4 <unknown>

[2024-12-27T11:44:16.245+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 101, in movie_page_extract
    driver.close()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 495, in close
    self.execute(Command.CLOSE)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
#0 0x5565781678fa <unknown>
#1 0x556577c78b7d <unknown>
#2 0x556577cba057 <unknown>
#3 0x556577cbb32e <unknown>
#4 0x55657813400b <unknown>
#5 0x556578137f97 <unknown>
#6 0x55657812071c <unknown>
#7 0x556578138b17 <unknown>
#8 0x5565781056cf <unknown>
#9 0x5565781566b8 <unknown>
#10 0x556578156880 <unknown>
#11 0x556578166776 <unknown>
#12 0x7faf68d181c4 <unknown>

[2024-12-27T11:44:16.285+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=scrape_movies, run_id=manual__2024-12-27T11:38:32.797674+00:00, execution_date=20241227T113832, start_date=20241227T114355, end_date=20241227T114416
[2024-12-27T11:44:16.318+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-27T11:44:16.321+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task scrape_movies (Message: invalid session id
Stacktrace:
#0 0x5565781678fa <unknown>
#1 0x556577c78b7d <unknown>
#2 0x556577cba057 <unknown>
#3 0x556577cbb32e <unknown>
#4 0x55657813400b <unknown>
#5 0x556578137f97 <unknown>
#6 0x55657812071c <unknown>
#7 0x556578138b17 <unknown>
#8 0x5565781056cf <unknown>
#9 0x5565781566b8 <unknown>
#10 0x556578156880 <unknown>
#11 0x556578166776 <unknown>
#12 0x7faf68d181c4 <unknown>
; 1083)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 101, in movie_page_extract
    driver.close()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 495, in close
    self.execute(Command.CLOSE)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
#0 0x5565781678fa <unknown>
#1 0x556577c78b7d <unknown>
#2 0x556577cba057 <unknown>
#3 0x556577cbb32e <unknown>
#4 0x55657813400b <unknown>
#5 0x556578137f97 <unknown>
#6 0x55657812071c <unknown>
#7 0x556578138b17 <unknown>
#8 0x5565781056cf <unknown>
#9 0x5565781566b8 <unknown>
#10 0x556578156880 <unknown>
#11 0x556578166776 <unknown>
#12 0x7faf68d181c4 <unknown>

[2024-12-27T11:44:16.367+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-27T11:44:16.454+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-27T11:44:16.464+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
