[2025-01-16T15:22:02.847+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-16T15:22:03.029+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_movies manual__2025-01-16T04:38:13.822674+00:00 [queued]>
[2025-01-16T15:22:03.063+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_movies manual__2025-01-16T04:38:13.822674+00:00 [queued]>
[2025-01-16T15:22:03.066+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-16T15:22:03.112+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_movies> on 2025-01-16 04:38:13.822674+00:00
[2025-01-16T15:22:03.132+0000] {standard_task_runner.py:72} INFO - Started process 213 to run task
[2025-01-16T15:22:03.156+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_movies', 'manual__2025-01-16T04:38:13.822674+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmprrt_de2a']
[2025-01-16T15:22:03.205+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask scrape_movies
[2025-01-16T15:22:03.947+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_movies manual__2025-01-16T04:38:13.822674+00:00 [running]> on host 2dad824ef9ce
[2025-01-16T15:22:04.464+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_movies' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T04:38:13.822674+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T04:38:13.822674+00:00'
[2025-01-16T15:22:04.468+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-16T15:22:12.160+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract_scripts/extract.py", line 55, in movie_page_extract
    s3_data=s3.get_object(Bucket=collection_parsed_fp.split('/')[2],Key='/'.join(collection_parsed_fp.split('/')[3:])).read().decode('utf-8')
AttributeError: 'dict' object has no attribute 'read'
[2025-01-16T15:22:12.214+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=scrape_movies, run_id=manual__2025-01-16T04:38:13.822674+00:00, execution_date=20250116T043813, start_date=20250116T152203, end_date=20250116T152212
[2025-01-16T15:22:12.262+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-16T15:22:12.266+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task scrape_movies ('dict' object has no attribute 'read'; 213)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract_scripts/extract.py", line 55, in movie_page_extract
    s3_data=s3.get_object(Bucket=collection_parsed_fp.split('/')[2],Key='/'.join(collection_parsed_fp.split('/')[3:])).read().decode('utf-8')
AttributeError: 'dict' object has no attribute 'read'
[2025-01-16T15:22:12.301+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-16T15:22:12.390+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T15:22:12.400+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
