[2024-12-29T04:29:41.067+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-29T04:29:41.386+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_distributors scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T04:29:41.421+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_distributors scheduled__2024-12-28T00:00:00+00:00 [queued]>
[2024-12-29T04:29:41.429+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-29T04:29:41.478+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_distributors> on 2024-12-28 00:00:00+00:00
[2024-12-29T04:29:41.494+0000] {standard_task_runner.py:72} INFO - Started process 1872 to run task
[2024-12-29T04:29:41.502+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_distributors', 'scheduled__2024-12-28T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpnxrvnfad']
[2024-12-29T04:29:41.507+0000] {standard_task_runner.py:105} INFO - Job 110: Subtask scrape_distributors
[2024-12-29T04:29:41.699+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_distributors scheduled__2024-12-28T00:00:00+00:00 [running]> on host e0a3add0f1ca
[2024-12-29T04:29:42.374+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_distributors' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T00:00:00+00:00'
[2024-12-29T04:29:42.383+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-29T04:29:45.626+0000] {extract.py:319} INFO - Iteration: 0 and movie_id: tt13186482
[2024-12-29T04:30:08.128+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-29T04:30:08.383+0000] {process_utils.py:132} INFO - Sending 15 to group 1872. PIDs of all processes in the group: [1916, 1946, 1950, 1951, 1985, 1990, 2111, 2052, 2125, 2213, 2300, 2103, 1872]
[2024-12-29T04:30:08.421+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1872
[2024-12-29T04:30:08.451+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-29T04:30:08.696+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-29T04:30:08.713+0000] {connectionpool.py:827} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd34f3970>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2fd5554881fdf7b512f9ccde3034f549/window
[2024-12-29T04:30:08.717+0000] {process_utils.py:132} INFO - Sending 15 to group 1872. PIDs of all processes in the group: [1916, 1872]
[2024-12-29T04:30:08.723+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1872
[2024-12-29T04:30:08.720+0000] {connectionpool.py:827} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd34f3a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2fd5554881fdf7b512f9ccde3034f549/window
