[2024-12-25T09:59:34.434+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-25T09:59:34.863+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_collection_page scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T09:59:34.887+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_collection_page scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T09:59:34.891+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-25T09:59:34.922+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_collection_page> on 2024-12-24 00:00:00+00:00
[2024-12-25T09:59:34.931+0000] {standard_task_runner.py:72} INFO - Started process 202 to run task
[2024-12-25T09:59:34.941+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_collection_page', 'scheduled__2024-12-24T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpxn7wfhnz']
[2024-12-25T09:59:34.948+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask scrape_collection_page
[2024-12-25T09:59:35.141+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_collection_page scheduled__2024-12-24T00:00:00+00:00 [running]> on host 0efa8e9b8229
[2024-12-25T09:59:35.387+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_collection_page' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-24T00:00:00+00:00'
[2024-12-25T09:59:35.391+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-25T09:59:35.412+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 16, in page_extract
    driver=webdriver.Chrome(service=service)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self._start_process(self._path)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 214, in _start_process
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './chromedriver'
[2024-12-25T09:59:35.445+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=scrape_collection_page, run_id=scheduled__2024-12-24T00:00:00+00:00, execution_date=20241224T000000, start_date=20241225T095934, end_date=20241225T095935
[2024-12-25T09:59:35.479+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-25T09:59:35.483+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task scrape_collection_page ([Errno 8] Exec format error: './chromedriver'; 202)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 16, in page_extract
    driver=webdriver.Chrome(service=service)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self._start_process(self._path)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 214, in _start_process
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './chromedriver'
[2024-12-25T09:59:35.513+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-25T09:59:35.571+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-25T09:59:35.596+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-25T10:35:34.480+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-25T10:35:34.756+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_collection_page scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T10:35:34.778+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_collection_page scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T10:35:34.780+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-25T10:35:34.815+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_collection_page> on 2024-12-24 00:00:00+00:00
[2024-12-25T10:35:34.828+0000] {standard_task_runner.py:72} INFO - Started process 965 to run task
[2024-12-25T10:35:34.841+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_collection_page', 'scheduled__2024-12-24T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp2tvev0ox']
[2024-12-25T10:35:34.847+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask scrape_collection_page
[2024-12-25T10:35:35.033+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_collection_page scheduled__2024-12-24T00:00:00+00:00 [running]> on host 0efa8e9b8229
[2024-12-25T10:35:35.245+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_collection_page' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-24T00:00:00+00:00'
[2024-12-25T10:35:35.248+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-25T10:35:35.271+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 214, in _start_process
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'chromedriver'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 16, in page_extract
    driver=webdriver.Chrome(service=service)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self._start_process(self._path)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 238, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.

[2024-12-25T10:35:35.313+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=scrape_collection_page, run_id=scheduled__2024-12-24T00:00:00+00:00, execution_date=20241224T000000, start_date=20241225T103534, end_date=20241225T103535
[2024-12-25T10:35:35.344+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-25T10:35:35.347+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task scrape_collection_page (Message: 'chromedriver' executable may have wrong permissions.
; 965)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 214, in _start_process
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'chromedriver'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 16, in page_extract
    driver=webdriver.Chrome(service=service)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self._start_process(self._path)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 238, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions.

[2024-12-25T10:35:35.396+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-25T10:35:35.481+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-25T10:35:35.494+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
