[2024-12-28T08:06:07.317+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T08:06:10.005+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_genre manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-28T08:06:10.036+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_genre manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-28T08:06:10.040+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2024-12-28T08:06:11.129+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_genre> on 2024-12-27 11:38:32.797674+00:00
[2024-12-28T08:06:11.148+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_genre', 'manual__2024-12-27T11:38:32.797674+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp071wsur_']
[2024-12-28T08:06:11.142+0000] {standard_task_runner.py:72} INFO - Started process 267 to run task
[2024-12-28T08:06:11.166+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask scrape_genre
[2024-12-28T08:06:11.540+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_genre manual__2024-12-27T11:38:32.797674+00:00 [running]> on host f96043a2d07e
[2024-12-28T08:06:12.082+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_genre' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T11:38:32.797674+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T11:38:32.797674+00:00'
[2024-12-28T08:06:12.085+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T08:06:27.424+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 199, in genre_scraper
    driver=webdriver.Chrome(options=options)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55c1768bb8fa <unknown>
#1 0x55c1763ccd20 <unknown>
#2 0x55c176404438 <unknown>
#3 0x55c1763fff96 <unknown>
#4 0x55c17644bd86 <unknown>
#5 0x55c17644b3d6 <unknown>
#6 0x55c17643f893 <unknown>
#7 0x55c17640e30d <unknown>
#8 0x55c17640f32e <unknown>
#9 0x55c17688800b <unknown>
#10 0x55c17688bf97 <unknown>
#11 0x55c17687471c <unknown>
#12 0x55c17688cb17 <unknown>
#13 0x55c1768596cf <unknown>
#14 0x55c1768aa6b8 <unknown>
#15 0x55c1768aa880 <unknown>
#16 0x55c1768ba776 <unknown>
#17 0x7f507090e1c4 <unknown>

[2024-12-28T08:06:27.504+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=scrape_genre, run_id=manual__2024-12-27T11:38:32.797674+00:00, execution_date=20241227T113832, start_date=20241228T080610, end_date=20241228T080627
[2024-12-28T08:06:27.558+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T08:06:27.562+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 87 for task scrape_genre (Message: session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55c1768bb8fa <unknown>
#1 0x55c1763ccd20 <unknown>
#2 0x55c176404438 <unknown>
#3 0x55c1763fff96 <unknown>
#4 0x55c17644bd86 <unknown>
#5 0x55c17644b3d6 <unknown>
#6 0x55c17643f893 <unknown>
#7 0x55c17640e30d <unknown>
#8 0x55c17640f32e <unknown>
#9 0x55c17688800b <unknown>
#10 0x55c17688bf97 <unknown>
#11 0x55c17687471c <unknown>
#12 0x55c17688cb17 <unknown>
#13 0x55c1768596cf <unknown>
#14 0x55c1768aa6b8 <unknown>
#15 0x55c1768aa880 <unknown>
#16 0x55c1768ba776 <unknown>
#17 0x7f507090e1c4 <unknown>
; 267)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 199, in genre_scraper
    driver=webdriver.Chrome(options=options)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55c1768bb8fa <unknown>
#1 0x55c1763ccd20 <unknown>
#2 0x55c176404438 <unknown>
#3 0x55c1763fff96 <unknown>
#4 0x55c17644bd86 <unknown>
#5 0x55c17644b3d6 <unknown>
#6 0x55c17643f893 <unknown>
#7 0x55c17640e30d <unknown>
#8 0x55c17640f32e <unknown>
#9 0x55c17688800b <unknown>
#10 0x55c17688bf97 <unknown>
#11 0x55c17687471c <unknown>
#12 0x55c17688cb17 <unknown>
#13 0x55c1768596cf <unknown>
#14 0x55c1768aa6b8 <unknown>
#15 0x55c1768aa880 <unknown>
#16 0x55c1768ba776 <unknown>
#17 0x7f507090e1c4 <unknown>

[2024-12-28T08:06:27.587+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T08:06:27.682+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T08:06:27.692+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
