[2024-12-28T08:29:23.563+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T08:29:23.818+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.scrape_genre manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-28T08:29:23.837+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.scrape_genre manual__2024-12-27T11:38:32.797674+00:00 [queued]>
[2024-12-28T08:29:23.842+0000] {taskinstance.py:2866} INFO - Starting attempt 5 of 5
[2024-12-28T08:29:23.868+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_genre> on 2024-12-27 11:38:32.797674+00:00
[2024-12-28T08:29:23.879+0000] {standard_task_runner.py:72} INFO - Started process 623 to run task
[2024-12-28T08:29:23.885+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'scrape_genre', 'manual__2024-12-27T11:38:32.797674+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpi2ffci1t']
[2024-12-28T08:29:23.890+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask scrape_genre
[2024-12-28T08:29:24.866+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.scrape_genre manual__2024-12-27T11:38:32.797674+00:00 [running]> on host 4ea37e791498
[2024-12-28T08:29:25.336+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='scrape_genre' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T11:38:32.797674+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T11:38:32.797674+00:00'
[2024-12-28T08:29:25.341+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T08:29:30.557+0000] {extract.py:235} INFO - movie_iteration: 0, genre_iteration0 for movie_id: tt13186482 and genre_id: in0000092
[2024-12-28T08:29:32.964+0000] {extract.py:260} ERROR - Failed movie_iteration: 0, genre_iteration 0 for movie_id: tt13186482 and genre_id: in0000092
[2024-12-28T08:29:32.965+0000] {extract.py:261} ERROR - Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x5587e9fa08fa <unknown>
#1 0x5587e9ab1b7d <unknown>
#2 0x5587e9a9b45e <unknown>
#3 0x5587e9a9a65e <unknown>
#4 0x5587e9a99dd6 <unknown>
#5 0x5587e9a99cce <unknown>
#6 0x5587e9a97d06 <unknown>
#7 0x5587e9a984ef <unknown>
#8 0x5587e9aa7d87 <unknown>
#9 0x5587e9abebb4 <unknown>
#10 0x5587e9ac4a4b <unknown>
#11 0x5587e9a98bf7 <unknown>
#12 0x5587e9abe701 <unknown>
#13 0x5587e9b438df <unknown>
#14 0x5587e9b24893 <unknown>
#15 0x5587e9af330d <unknown>
#16 0x5587e9af432e <unknown>
#17 0x5587e9f6d00b <unknown>
#18 0x5587e9f70f97 <unknown>
#19 0x5587e9f5971c <unknown>
#20 0x5587e9f71b17 <unknown>
#21 0x5587e9f3e6cf <unknown>
#22 0x5587e9f8f6b8 <unknown>
#23 0x5587e9f8f880 <unknown>
#24 0x5587e9f9f776 <unknown>
#25 0x7feaafeee1c4 <unknown>
Traceback (most recent call last):
  File "/opt/src/extract.py", line 238, in genre_scraper
    driver.get(genre_link_num_of_rating_sorted)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=131.0.6778.204)
Stacktrace:
#0 0x5587e9fa08fa <unknown>
#1 0x5587e9ab1b7d <unknown>
#2 0x5587e9a9b45e <unknown>
#3 0x5587e9a9a65e <unknown>
#4 0x5587e9a99dd6 <unknown>
#5 0x5587e9a99cce <unknown>
#6 0x5587e9a97d06 <unknown>
#7 0x5587e9a984ef <unknown>
#8 0x5587e9aa7d87 <unknown>
#9 0x5587e9abebb4 <unknown>
#10 0x5587e9ac4a4b <unknown>
#11 0x5587e9a98bf7 <unknown>
#12 0x5587e9abe701 <unknown>
#13 0x5587e9b438df <unknown>
#14 0x5587e9b24893 <unknown>
#15 0x5587e9af330d <unknown>
#16 0x5587e9af432e <unknown>
#17 0x5587e9f6d00b <unknown>
#18 0x5587e9f70f97 <unknown>
#19 0x5587e9f5971c <unknown>
#20 0x5587e9f71b17 <unknown>
#21 0x5587e9f3e6cf <unknown>
#22 0x5587e9f8f6b8 <unknown>
#23 0x5587e9f8f880 <unknown>
#24 0x5587e9f9f776 <unknown>
#25 0x7feaafeee1c4 <unknown>

[2024-12-28T08:29:32.984+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 263, in genre_scraper
    driver.close()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 495, in close
    self.execute(Command.CLOSE)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
#0 0x5587e9fa08fa <unknown>
#1 0x5587e9ab1b7d <unknown>
#2 0x5587e9af3057 <unknown>
#3 0x5587e9af432e <unknown>
#4 0x5587e9f6d00b <unknown>
#5 0x5587e9f70f97 <unknown>
#6 0x5587e9f5971c <unknown>
#7 0x5587e9f71b17 <unknown>
#8 0x5587e9f3e6cf <unknown>
#9 0x5587e9f8f6b8 <unknown>
#10 0x5587e9f8f880 <unknown>
#11 0x5587e9f9f776 <unknown>
#12 0x7feaafeee1c4 <unknown>

[2024-12-28T08:29:33.036+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=scrape_genre, run_id=manual__2024-12-27T11:38:32.797674+00:00, execution_date=20241227T113832, start_date=20241228T082923, end_date=20241228T082933
[2024-12-28T08:29:33.076+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T08:29:33.080+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 90 for task scrape_genre (Message: invalid session id
Stacktrace:
#0 0x5587e9fa08fa <unknown>
#1 0x5587e9ab1b7d <unknown>
#2 0x5587e9af3057 <unknown>
#3 0x5587e9af432e <unknown>
#4 0x5587e9f6d00b <unknown>
#5 0x5587e9f70f97 <unknown>
#6 0x5587e9f5971c <unknown>
#7 0x5587e9f71b17 <unknown>
#8 0x5587e9f3e6cf <unknown>
#9 0x5587e9f8f6b8 <unknown>
#10 0x5587e9f8f880 <unknown>
#11 0x5587e9f9f776 <unknown>
#12 0x7feaafeee1c4 <unknown>
; 623)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/extract.py", line 263, in genre_scraper
    driver.close()
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 495, in close
    self.execute(Command.CLOSE)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
#0 0x5587e9fa08fa <unknown>
#1 0x5587e9ab1b7d <unknown>
#2 0x5587e9af3057 <unknown>
#3 0x5587e9af432e <unknown>
#4 0x5587e9f6d00b <unknown>
#5 0x5587e9f70f97 <unknown>
#6 0x5587e9f5971c <unknown>
#7 0x5587e9f71b17 <unknown>
#8 0x5587e9f3e6cf <unknown>
#9 0x5587e9f8f6b8 <unknown>
#10 0x5587e9f8f880 <unknown>
#11 0x5587e9f9f776 <unknown>
#12 0x7feaafeee1c4 <unknown>

[2024-12-28T08:29:33.116+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T08:29:33.157+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
