[2024-12-25T09:59:31.724+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-25T09:59:31.999+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.create_run_dir scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T09:59:32.021+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.create_run_dir scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T09:59:32.025+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-25T09:59:32.051+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_run_dir> on 2024-12-24 00:00:00+00:00
[2024-12-25T09:59:32.058+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2024-12-25T09:59:32.065+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'create_run_dir', 'scheduled__2024-12-24T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpic8r12o7']
[2024-12-25T09:59:32.069+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask create_run_dir
[2024-12-25T09:59:32.242+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.create_run_dir scheduled__2024-12-24T00:00:00+00:00 [running]> on host 0efa8e9b8229
[2024-12-25T09:59:32.545+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='create_run_dir' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-24T00:00:00+00:00'
[2024-12-25T09:59:32.549+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-25T09:59:32.557+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-25T09:59:32.588+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-25T09:59:32.590+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=movie_pipeline, task_id=create_run_dir, run_id=scheduled__2024-12-24T00:00:00+00:00, execution_date=20241224T000000, start_date=20241225T095932, end_date=20241225T095932
[2024-12-25T09:59:32.660+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-25T09:59:32.725+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-25T09:59:32.729+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-25T10:13:03.932+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-25T10:13:04.160+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.create_run_dir scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T10:13:04.177+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.create_run_dir scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T10:13:04.178+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-25T10:13:04.202+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_run_dir> on 2024-12-24 00:00:00+00:00
[2024-12-25T10:13:04.210+0000] {standard_task_runner.py:72} INFO - Started process 514 to run task
[2024-12-25T10:13:04.216+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'create_run_dir', 'scheduled__2024-12-24T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpt63fp7vb']
[2024-12-25T10:13:04.220+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask create_run_dir
[2024-12-25T10:13:04.344+0000] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.create_run_dir scheduled__2024-12-24T00:00:00+00:00 [running]> on host 0efa8e9b8229
[2024-12-25T10:13:04.597+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='create_run_dir' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-24T00:00:00+00:00'
[2024-12-25T10:13:04.607+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-25T10:13:04.621+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/Airflow/dags/pipeline_dag.py", line 23, in gen_dir
    os.mkdir(f"./run_{date.replace('-','')}")
FileExistsError: [Errno 17] File exists: './run_20241224'
[2024-12-25T10:13:04.657+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=create_run_dir, run_id=scheduled__2024-12-24T00:00:00+00:00, execution_date=20241224T000000, start_date=20241225T101304, end_date=20241225T101304
[2024-12-25T10:13:04.682+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-25T10:13:04.685+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task create_run_dir ([Errno 17] File exists: './run_20241224'; 514)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/src/Airflow/dags/pipeline_dag.py", line 23, in gen_dir
    os.mkdir(f"./run_{date.replace('-','')}")
FileExistsError: [Errno 17] File exists: './run_20241224'
[2024-12-25T10:13:04.731+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-25T10:13:04.793+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-25T10:13:04.805+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
