[2024-12-17T08:04:52.935+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-17T08:04:52.953+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_pipeline.logical_date_render manual__2024-12-17T02:34:42+00:00 [queued]>
[2024-12-17T08:04:52.964+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_pipeline.logical_date_render manual__2024-12-17T02:34:42+00:00 [queued]>
[2024-12-17T08:04:52.964+0530] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-17T08:04:52.978+0530] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): logical_date_render> on 2024-12-17 02:34:42+00:00
[2024-12-17T08:04:52.990+0530] {logging_mixin.py:190} WARNING - /Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=34780) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-17T08:04:52.991+0530] {standard_task_runner.py:72} INFO - Started process 34797 to run task
[2024-12-17T08:04:52.992+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'movie_pipeline', 'logical_date_render', 'manual__2024-12-17T02:34:42+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/var/folders/h6/l2cjrfls77b6_h6zs5w5vn4r0000gn/T/tmpn7r1f99c']
[2024-12-17T08:04:52.996+0530] {standard_task_runner.py:105} INFO - Job 158: Subtask logical_date_render
[2024-12-17T08:04:53.136+0530] {task_command.py:467} INFO - Running <TaskInstance: movie_pipeline.logical_date_render manual__2024-12-17T02:34:42+00:00 [running]> on host Jayeshs-MacBook-Air.local
[2024-12-17T08:04:53.208+0530] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='movie_pipeline' AIRFLOW_CTX_TASK_ID='logical_date_render' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T02:34:42+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T02:34:42+00:00'
[2024-12-17T08:04:53.210+0530] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-17T08:04:53.211+0530] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-17T08:04:53.212+0530] {logging_mixin.py:190} INFO - Current task name:logical_date_render state:running start_date:2024-12-17 02:34:52.954040+00:00
[2024-12-17T08:04:53.212+0530] {logging_mixin.py:190} INFO - Dag name:movie_pipeline and current dag run status:running
[2024-12-17T08:04:53.213+0530] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-17T08:04:53.214+0530] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/h6/l2cjrfls77b6_h6zs5w5vn4r0000gn/T
[2024-12-17T08:04:53.215+0530] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'python controller.py --run-date 2024-12-17']
[2024-12-17T08:04:53.221+0530] {subprocess.py:99} INFO - Output:
[2024-12-17T08:04:57.261+0530] {subprocess.py:106} INFO - usage: controller.py [-h] --run_date RUN_DATE
[2024-12-17T08:04:57.266+0530] {subprocess.py:106} INFO - controller.py: error: the following arguments are required: --run_date
[2024-12-17T08:04:57.582+0530] {subprocess.py:110} INFO - Command exited with return code 2
[2024-12-17T08:04:57.593+0530] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-17T08:04:57.609+0530] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-17T08:04:57.609+0530] {logging_mixin.py:190} INFO - Task start:2024-12-17 02:34:52.954040+00:00 end:2024-12-17 02:34:57.608224+00:00 duration:4.654184
[2024-12-17T08:04:57.610+0530] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): logical_date_render> dag:<DAG: movie_pipeline> dagrun:<DagRun movie_pipeline @ 2024-12-17 02:34:42+00:00: manual__2024-12-17T02:34:42+00:00, state:running, queued_at: 2024-12-17 02:34:42.726548+00:00. externally triggered: True>
[2024-12-17T08:04:57.611+0530] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2024-12-17T08:04:57.615+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movie_pipeline, task_id=logical_date_render, run_id=manual__2024-12-17T02:34:42+00:00, execution_date=20241217T023442, start_date=20241217T023452, end_date=20241217T023457
[2024-12-17T08:04:57.635+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-17T08:04:57.638+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 158 for task logical_date_render (Bash command failed. The command returned a non-zero exit code 2.; 34797)
Traceback (most recent call last):
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jayesh/Desktop/Personal Work/Movie_data_pipeline/.venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-17T08:04:57.661+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-17T08:04:57.702+0530] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-17T08:04:57.713+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
